[build]
  command = "chmod +x netlify/build.sh && netlify/build.sh"
  publish = "static"
  functions = "netlify/functions"

[dev]
  command = "python src/app.py"
  port = 5000
  publish = "static"
  autoLaunch = true

[[redirects]]
  from = "/v1/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/"
  to = "/.netlify/functions/api"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 